<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'title_bn',
        'content',
        'content_bn',
        'image',
        'date',
        'date_bn',
        'type',
        'related_id',
        'related_type',
        'is_active'
    ];

    protected $casts = [
        'date' => 'date',
        'is_active' => 'boolean'
    ];

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function scopeManual($query)
    {
        return $query->where('type', 'manual');
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('type', 'like', 'auto_%');
    }

    public function related()
    {
        return $this->morphTo();
    }
}